packageExtensions:
  '@chakra-ui/styled-system@*':
    dependencies:
      lodash.mergewith: '*'
  '@reach/visually-hidden@*':
    dependencies:
      prop-types: '*'
  '@types/node@*':
    dependencies:
      events: '*'
      url: '*'
      util: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  promise-inflight@*:
    dependencies:
      bluebird: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'

pnpMode: strict

yarnPath: .yarn/releases/yarn-2.4.0.cjs
